language:  python

python:
  - "2.7"
  - pypy

before_script:
  - sudo apt-get install -qq pdftk
  - sudo apt-get install -qq poppler-utils

script: 
  - bash build_test.sh python-$TRAVIS_PYTHON_VERSION


notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
